# SCOPE
included:
  - App
  - Core
  - Features

excluded:
  - Supporting
  - Resources
  - .git

# DISABLED RULES
disabled_rules:
  - redundant_self
  - closure_parameter_position
  - cyclomatic_complexity
  - file_length
  - function_body_length
  - function_parameter_count
  - identifier_name
  - large_tuple
  - multiple_closures_with_trailing_closure
  - nesting
  - todo
  - type_body_length

# OPT-IN RULES
opt_in_rules:
  # Safety
  - force_unwrapping
  - implicitly_unwrapped_optional
  - fatal_error_message

  # Performance
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_count
  - empty_string
  - first_where
  - flatmap_over_map_reduce
  - last_where
  - sorted_first_last

  # Formatting (auto-fixable)
  - closure_end_indentation
  - closure_spacing
  - comma_inheritance
  - direct_return
  - modifier_order
  - multiline_arguments
  - multiline_literal_brackets
  - operator_usage_whitespace
  - period_spacing
  - prefer_self_in_static_references
  - redundant_type_annotation
  - return_arrow_whitespace
  - shorthand_optional_binding
  - sorted_imports
  - syntactic_sugar
  - toggle_bool
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

  # Formatting (manual)
  - attributes
  - yoda_condition

  # SwiftUI
  - private_swiftui_state

  # Code Quality
  - convenience_type
  - identical_operands
  - local_doc_comment
  - superfluous_else
  - redundant_nil_coalescing

# ANALYZER RULES
analyzer_rules:
  - unused_declaration
  - unused_import

# CONFIGURATIONS
force_cast: error
force_try: error

line_length:
  warning: 150
  error: 200
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true
  ignores_multiline_strings: true

type_name:
  min_length: 3
  max_length: 50

implicitly_unwrapped_optional:
  mode: all

vertical_whitespace:
  max_empty_lines: 2

multiline_arguments:
  first_argument_location: next_line
  only_enforce_after_first_closure_on_first_line: true

attributes:
  always_on_same_line:
    - "@Environment"
    - "@State"
    - "@Binding"
    - "@Bindable"
    - "@Query"
  always_on_line_above:
    - "@MainActor"
    - "@Observable"
    - "@Sendable"
    - "@ViewBuilder"
    - "@discardableResult"
    - "@available"
    - "@ObservationIgnored"

trailing_comma:
  mandatory_comma: true

modifier_order:
  preferred_modifier_order:
    - override
    - isolation
    - acl
    - setterACL
    - dynamic
    - mutators
    - lazy
    - final
    - required
    - convenience
    - typeMethods
    - owned

reporter: xcode

# CUSTOM RULES
custom_rules:
  no_print:
    name: "No Print Statements"
    regex: "(print\\(|debugPrint\\(|NSLog\\()"
    message: "Use os.Logger instead of print/debugPrint/NSLog"
    severity: warning

  no_combine:
    name: "No Combine"
    regex: "^import Combine"
    message: "Combine is not allowed. Use async/await and @Observable instead."
    severity: error
